config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
                                    message: '%<value> is not a valid category'
                                  }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action: :find, only: [:show, :edit, :create, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # resources :reviews, only: %i[new create]
    # we dont need a restaurant id to run the destroy review
  before_action :find_restaurant, except: [:destroy]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need to associate our review to a restaurant(restaurant_id)
    # because so far this is what we have: <Review id: nil, rating: 5, content: "amazing", restaurant_id: nil, created_at: nil, updated_at: nil>
    # in the console: new_review.restaurant = eatery
    @review.restaurant = @restaurant
    # if not empty due to validations it will save. then:
    # raise
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # we will stay in the create action but will display the template of the new page
      # the only difference is that i am not using the "new" instance of @review, i am
      # using the instance of review that failed to save.
      # we can look at this instance on rails c using new_review.errors.messages
      # simple form handles that
      # render renders some html, it renders a page
      # if THE SAVE fails it will render a new page, and what is this new page?
      # essentially my form.
      # this instance of @review has validations and will show errors
      # renders the "new" route, a new form
      render :new
    end
  end

  private

  def find_restaurant
    # in our routes for reviews it is :restaurant_id
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

# to generate the route we need in our simple form
# we are gonna  add the restaurant instead of @review.
# so we will pass an array with BOTH [@restaurant,@review]
# to generate the route that we want

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- app/views/layouts/application.html.erb -->

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- [...] -->

    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<br>
<%= link_to 'Create a new Restaurant', new_restaurant_path, class: "btn btn-secondary" %>
<br>
<br>
<% @restaurants.each do |restaurant| %>
  <h5><%= link_to restaurant.name, restaurant_path(restaurant)%> <%= restaurant.category %></h5>
  <p><%= restaurant.address%></p>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>
<hr>
<%= link_to 'Back to restaurants', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> <%= '⭐' + @restaurant.category%></h1>
  <p><%= @restaurant.address%></p>

  <%# iterates over the reviews %>
  <%# HOW CAN I ITERATE OVER THE REVIEWS? I HAVE MY RESTAURANT INSTANCE... %>
  <%#= restaurant.reviews PORQUE EU FIZ ESSA ASSOCAÇÃO NO MODELO RESTAURANT %>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %></li>
      <%# <%= link_to 'create', review_path(review), method: :post, data: { confirm: "Are you sure?" } %>
      <hr>
    <% end %>
  </ul>

<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>
<hr>
<%= link_to 'Back to restaurants', restaurants_path %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <!-- adds bootstrap button  -->
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<!-- we need: -->
<!-- <form action="/restaurants/101/reviews/new" method="post"></form> -->
<%# simple_form_for [@review] %>
<!-- this will generate a form with action 'reviews' only! -->
<!-- which will return error: undefined method `reviews_path'  -->
<!-- that would give us a '/reviews' and we don't have that in our routes -->
<!-- in our routes we have: -->
<!-- /restaurants/:restaurant_id/reviews
/restaurants/:restaurant_id/reviews/new -->
<!-- we need action '/restaurants/:id/reviews/new' -->

<!-- we dont have any references added to our restaurant model. We need
to get the id!! -->

<!-- WHAT TO DO: -->
<!-- - find restaurant in the reviews controller; -->
<!-- GO BACK TO TEACHER.MD -->

<%#
Helper	HTTP request
simple_form_for(@review)	POST reviews_path (does not exist)
simple_form_for([@restaurant, @review])	POST restaurant_reviews_path %>